keys:
  - &host_nyx-pad_age age16dn2c2p9zv6k2q7wyqshpe7l86lckm0af3d76mgr5d7576zp65rs5fvudy
  - &host_nyx-server_age age1vqxmneswassf5wyj7q806l8x0tulansn5drna4plwhk908w4gd8s57l977
creation_rules:
  - path_regex: nyx-pad.ya?ml$
    key_groups:
      - age:
        - *host_nyx-pad_age
  - path_regex: nyx-server.ya?ml$
    key_groups:
      - age:
        - *host_nyx-server_age
