keys:
  - &host_nyx-pad_age age1d6et82mzmpd224wdveecskrw22s853cp2pwdny3vesrlnv6vd4gq07xsfd
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *host_nyx-pad_age
