command_key = ":"
initial_screen = "library"
use_nerdfont = true
#backend = ""
#backend_device = ""
audio_cache = true
audio_cache_size = 512
volnorm = true
volnorm_pregain = 0.0
default_keybindings = true
notify = false
bitrate = 320
gapless = true
shuffle = true
repeat = "playlist"
playback_state = "Paused"
library_tabs = [ "tracks", "albums", "artists", "playlists", "browse" ]
cover_max_scale = 1.0
hide_display_name = false
statusbar_format = "%artists - %track"